### ISSUE TITLE
[bug] android display cached version of tweet

### ISSUE THREAD

**Issue by thedgbrt** [netceteragroup/react-native-twitterkit#13]
There used to be a fix for it in TweetView.java, in a [previous version](https://github.com/netceteragroup/react-native-twitterkit/blob/4af05f6c68823a78a5cc33a92948b326ff7ba652/android/src/main/java/com/netcetera/reactnative/twitterkit/TweetView.java).

Since then, the method for displaying a tweet in Android changed, and the fix is gone. I get the bug very often.

Is there a way to fix it? I can take a stab at it if somebody guides me with the approach, as I'm not an Android developer at all.

![28084840-35a64268-667a-11e7-8774-bfbf9ade150f](https://user-images.githubusercontent.com/1362558/28118807-e0266c3e-6712-11e7-8fa2-49544d3d7ae1.png)

**Comment by ognen** [comment]
Hi @thedgbrt, 

Thank you for your report. I assume you are referring to the bug where the image isn't showing properly, correct? 

We ware moving to TwitterKit version 3, major change; as soon as I merge the pull requests I will let you know so you can re-test this issue. If it shows up with the newer twitter kit, we will investigate further.

**Comment by thedgbrt** [comment]
@ognen nope, the tweet that you see here is not the one i loaded, it's the one from the initializer. https://github.com/netceteragroup/react-native-twitterkit/blob/0a219af66a75d9967746f1f1b96c2f3a4367b22e/android/src/main/res/layout/tweet_container.xml

It happens from time to time when I load the app, and I noticed that in a previous version of the repo, it was a know issue, with a [workaround for it (see line 23)](https://github.com/netceteragroup/react-native-twitterkit/blob/4af05f6c68823a78a5cc33a92948b326ff7ba652/android/src/main/java/com/netcetera/reactnative/twitterkit/TweetView.java#L23).

Since TweetView has been refactored, the bug happens again.

(really cool that you're upgrading to twitterKit 3 👍, i'm thankful for all the work that's been done already)

**Comment by ognen** [comment]
@thedgbrt, yes, there is a fix for that in the #14 pull request (it wasn't done separately). Expect that TwitterKit 3.0 lands next week as soon as I verify that iOS / Android PRs work as expected.

**Comment by thedgbrt** [comment]
@ognen brilliant! thanks for pointing it out :)
